name: UnitTest

on:
  push:
    branches:
      - '**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Python
        with:
          python-version: 3.8
        run: |
          node --version
          py --version
          python --version
          python3 --version
