name: UnitTest

on:
  push:
    branches:
      - '**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls
          pip install -r ./backend/requirements.pip
      - name: Run unit tests
        run: |
          python -m pytest backend/test/unit/
